# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1504377fa5ca3a0a49fb970120d76ee003bd2ac6911975a98ba92905ba0c1ea2c17fa81e4a1f2d6f066c8da03fdfce3418acd91e2be066ce249741804bbd1c0

test:
  secret_key_base: 2d08bdb0106078703409c62b692310839a79b8becfe75ff808a358ffb716af3076a47a89ad922ae3e2569f3c2a5de32ae9d37636e1374ca8912c6ef477ce97df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
